### PR TITLE
Compatibility for require.js build system

### PR DESCRIPTION
**Pull request by paulwe**
Templates built with r.js crash because the jade object returned in define isn't a reference to the jade runtime...

### CODE REVIEW

**Comment by vincentmac** [comment]
Can you give me a little more context on the error you were having and how I can reproduce it?

**Comment by paulwe** [comment]
Make a template with a variable in it...

``` jade
span= foo
```

Add the directive suggested in the readme to the build config.

``` javascript
pragmasOnSave: {
  excludeJade: true
}
```

Build the app and try to execute the template function... it throws a type error while trying to execute undefined, the escape function in this case.

After reading the jade docs it seems it may not be necessary to include the jade library, the correct solution is to substitute jade's runtime.js for jade.js. It looks like this can be implemented by adding a [writeFile](http://requirejs.org/docs/plugins.html#writefile) method. The docs might suggest adding "optimizeAllPluginResources: true" to build configs...

**Comment by vincentmac** [comment]
Please look around `line 3710` in `jade.js`.  When you build your app with `r.js` and have the `excludeJade: true` flag in `pragmasOnSave` it should first compile your templates using the regular jade compiler and then include the jade runtime when saving the minified code to the output file.

Please see [this discussion](https://github.com/vincentmac/require-jade/pull/1).

r.js [example.build.js](https://github.com/jrburke/r.js/blob/master/build/example.build.js) see the section on `pragmas` and `pragmasOnSave` starting at `line 148`.

Please let me know if this helps you out.

**Comment by paulwe** [comment]
Thanks... As I mentioned before, the build directive was set correctly. The code you referenced appears in the the output file as expected. Unfortunately this is given as the definition for jade:

``` javascript
define('jade',{
        version: '0.0.1',
    load: function (name, parentRequire, load, config) {

    }
});
```

**Comment by hapticdata** [comment]
I can vouch for this issue and pull request.
Require-jade was working fine until being built with r.js, after that I was getting the error `undefined is not a function` coming from `attrs`. I had the config set with: `pragmasOnSave: { excludeJade: true }` . After switching to the fork by @paulwe  it worked correctly.

**Comment by vincentmac** [comment]
@hapticdata thanks for the feedback.

**Pull request merged**
