### PR TITLE
Upgraded jade dependency to 0.30.0

### PR DESCRIPTION
**Pull request by crissdev**
The jade dependency was upgraded to 0.30.0
I couldn't upgrade it to the latest version because there is a dependency hard to refactor - such as uglify-js

I didn't update the version in the package.json because it was already set to 0.0.2, though the file jade.js was specifying version 0.0.1

### CODE REVIEW

**Comment by deedubs** [comment]
LGTM @vincentmac?

**Comment by vincentmac** [comment]
@CrissDev Thanks.  I'll take a look at this in the morning.  If I don't get back to you by mid-afternoon (PST), please mention me again in this PR so I get a notification (and a reminder ;) ).

**Comment by deedubs** [comment]
Thanks @CrissDev & @vincentmac

**Comment by crissdev** [comment]
@vincentmac @deedubs Thanks for merging this. I'll try to push more updates in the future.

**Pull request merged**
