### PR TITLE
Refactored to support 'extends' and 'include' when doing single-file optimization with r.js

### PR DESCRIPTION
**Pull request by pheuter**
**Disclaimer:** _This is the result of hacking around core Jade and require-jade functionality. Let this pull request serve as a means to an end rather than the solution._
### Problem

Jade's template inheritance constructs, such as `extends` and `include`, are broken when using **require-jade**. See see issues [10](https://github.com/rocketlabsdev/require-jade/issues/10) and [11](https://github.com/rocketlabsdev/require-jade/issues/11).
### Proposed solution

Refactor `parseExtends` and `parseInclude` to leverage a modified, synchronous `fetchText`. 
### Idiosyncrasies

`parseExtends` and `parseInclude` need to know the baseUrl. I was unable to figure out a way to pass it in other than via `process`. That is why you see the following in `load`:

``` js
process.baseUrl = parentRequire.toUrl('.').slice(0, -1);
```

I'm sure there is a better way to accomplish this, I'm just not aware of it...

### CODE REVIEW

**Comment by vincentmac** [comment]
Nice.  I'll take a look at this when I get a chance.

**Comment by pheuter** [comment]
Awesome, would be great to have feedback asap, currently using **require-jade** for a large codebase.

**Comment by pheuter** [comment]
@vincentmac Would be great to get a status update on the pull request.

**Comment by paulyoung** [comment]
+1

**Comment by vincentmac** [comment]
Just a little update.  I started to look at this today.

Your changes are a good starting place and do, indeed, make template inheritance possible; however, the functionality only works after building with r.js.  Furthermore, it is breaking the plugin for every other use case.

When using the PR version of the plugin, I am getting the following error:
`Uncaught ReferenceError: process is not defined`

To keep this plugin upgradable in the future, I think it is very important not to modify any of the Jade source code (with the exception of exposing Jade as a global variable in line 3648).  I do like that you are overriding the function prototype rather than modifying the function directly.

The main problem I am seeing with template inheritance on the clientside, is that Jade uses [Node's path module](http://nodejs.org/api/path.html) to resolve file locations.  Looking at the PR, I can see that you already now that :).  I haven't dug too far into all of Jade's inner workings but I can see that it also uses Node's File System module.

I am not sure if modifying Jade directly is the right direction to solve this problem.  I too would love to have all of the same serverside functionality that Jade provides in the browser, however, we need to remember Jade is primarily a serverside templating engine.

If you want all of the serverside functionality of Jade, one possible solution for you could be [Browserify](https://github.com/substack/node-browserify).

Another option may be to only use Jade's runtime in your project and setup a build process to convert your templates to js files.

I'll try to take another look at this when I get more time.

**Comment by pheuter** [comment]
If anyone is interested I started work on [require-j](https://github.com/pheuter/require-j), a RequireJS jade plugin that supports template inheritance.

**Pull request closed without merging**
